import { expect, test } from "@playwright/test";

const mockedBoard = {
  columns: [
    { id: "col-backlog", title: "Backlog", cardIds: ["card-1", "card-2"] },
    { id: "col-discovery", title: "Discovery", cardIds: ["card-3"] },
    { id: "col-progress", title: "In Progress", cardIds: ["card-4", "card-5"] },
    { id: "col-review", title: "Review", cardIds: ["card-6"] },
    { id: "col-done", title: "Done", cardIds: ["card-7", "card-8"] },
  ],
  cards: {
    "card-1": {
      id: "card-1",
      title: "Align roadmap themes",
      details: "Draft quarterly themes with impact statements and metrics.",
    },
    "card-2": {
      id: "card-2",
      title: "Gather customer signals",
      details: "Review support tags, sales notes, and churn feedback.",
    },
    "card-3": {
      id: "card-3",
      title: "Prototype analytics view",
      details: "Sketch initial dashboard layout and key drill-downs.",
    },
    "card-4": {
      id: "card-4",
      title: "Refine status language",
      details: "Standardize column labels and tone across the board.",
    },
    "card-5": {
      id: "card-5",
      title: "Design card layout",
      details: "Add hierarchy and spacing for scanning dense lists.",
    },
    "card-6": {
      id: "card-6",
      title: "QA micro-interactions",
      details: "Verify hover, focus, and loading states.",
    },
    "card-7": {
      id: "card-7",
      title: "Ship marketing page",
      details: "Final copy approved and asset pack delivered.",
    },
    "card-8": {
      id: "card-8",
      title: "Close onboarding sprint",
      details: "Document release notes and share internally.",
    },
  },
};

const login = async (page: import("@playwright/test").Page) => {
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "Sign in" })).toBeVisible();
  await page.getByLabel("Username").fill("user");
  await page.getByLabel("Password").fill("password");
  await page.getByRole("button", { name: "Sign in" }).click();
  await expect(page.getByRole("heading", { name: "Kanban Studio" })).toBeVisible();
};

test("loads the kanban board", async ({ page }) => {
  await login(page);
  await expect(page.locator('[data-testid^="column-"]')).toHaveCount(5);
});

test("adds a card to a column", async ({ page }) => {
  await login(page);
  const firstColumn = page.locator('[data-testid^="column-"]').first();
  await firstColumn.getByRole("button", { name: /add a card/i }).click();
  await firstColumn.getByPlaceholder("Card title").fill("Playwright card");
  await firstColumn.getByPlaceholder("Details").fill("Added via e2e.");
  await firstColumn.getByRole("button", { name: /add card/i }).click();
  await expect(firstColumn.getByText("Playwright card")).toBeVisible();
});

test("moves a card between columns", async ({ page }) => {
  await login(page);
  const card = page.getByTestId("card-card-1");
  const targetColumn = page.getByTestId("column-col-review");
  const cardBox = await card.boundingBox();
  const columnBox = await targetColumn.boundingBox();
  if (!cardBox || !columnBox) {
    throw new Error("Unable to resolve drag coordinates.");
  }

  await page.mouse.move(
    cardBox.x + cardBox.width / 2,
    cardBox.y + cardBox.height / 2
  );
  await page.mouse.down();
  await page.mouse.move(
    columnBox.x + columnBox.width / 2,
    columnBox.y + 120,
    { steps: 12 }
  );
  await page.mouse.up();
  await expect(targetColumn.getByTestId("card-card-1")).toBeVisible();
});

test("ai chat updates the board after response", async ({ page }) => {
  const aiCardId = "card-ai-1";
  await page.route("**/api/auth/login", async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({ message: "Login successful" }),
    });
  });
  await page.route("**/api/auth/status", async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({ authenticated: true }),
    });
  });
  await page.route("**/api/board", async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify(mockedBoard),
    });
  });
  await page.route("**/api/ai/chat", async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({
        assistantMessage: "Added AI Follow-up in Backlog.",
        operations: [
          {
            type: "create_card",
            column_id: "col-backlog",
            card_id: null,
            title: "AI Follow-up",
            details: "Generated by AI",
            before_card_id: null,
          },
        ],
        board: {
          ...mockedBoard,
          columns: mockedBoard.columns.map((column, index) =>
            index === 0 ? { ...column, cardIds: [...column.cardIds, aiCardId] } : column
          ),
          cards: {
            ...mockedBoard.cards,
            [aiCardId]: {
              id: aiCardId,
              title: "AI Follow-up",
              details: "Generated by AI",
            },
          },
        },
      }),
    });
  });

  await login(page);
  await page.getByLabel("Ask AI").fill("Add AI Follow-up card to Backlog");
  await page.getByRole("button", { name: /send to ai/i }).click();

  await expect(page.getByText("Added AI Follow-up in Backlog.")).toBeVisible();
  await expect(page.getByTestId(`card-${aiCardId}`)).toBeVisible();
});

test("renames a column", async ({ page }) => {
  await page.route("**/api/auth/login", async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({ message: "Login successful" }),
    });
  });
  await page.route("**/api/auth/status", async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({ authenticated: true }),
    });
  });
  await page.route("**/api/board", async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify(mockedBoard),
    });
  });
  await page.route("**/api/columns/col-backlog", async (route) => {
    if (route.request().method() === "PATCH") {
      const updatedBoard = {
        ...mockedBoard,
        columns: mockedBoard.columns.map((col) =>
          col.id === "col-backlog" ? { ...col, title: "Ideas" } : col
        ),
      };
      await route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify(updatedBoard),
      });
    }
  });

  await login(page);
  const backlogColumn = page.getByTestId("column-col-backlog");
  await expect(backlogColumn.getByText("Backlog")).toBeVisible();
  
  const titleInput = backlogColumn.locator('input[aria-label="Column title"]');
  await titleInput.fill("Ideas");
  await titleInput.blur();

  await expect(backlogColumn.getByText("Ideas")).toBeVisible();
});

test("deletes a card", async ({ page }) => {
  const cardToDelete = "card-1";
  await page.route("**/api/auth/login", async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({ message: "Login successful" }),
    });
  });
  await page.route("**/api/auth/status", async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({ authenticated: true }),
    });
  });
  await page.route("**/api/board", async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify(mockedBoard),
    });
  });
  await page.route(/api\/columns\/col-backlog\/cards\/card-1/, async (route) => {
    if (route.request().method() === "DELETE") {
      const updatedBoard = {
        ...mockedBoard,
        columns: mockedBoard.columns.map((col) =>
          col.id === "col-backlog"
            ? { ...col, cardIds: col.cardIds.filter((id) => id !== cardToDelete) }
            : col
        ),
        cards: Object.fromEntries(
          Object.entries(mockedBoard.cards).filter(([id]) => id !== cardToDelete)
        ),
      };
      await route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify(updatedBoard),
      });
    }
  });

  await login(page);
  const card = page.getByTestId(`card-${cardToDelete}`);
  await expect(card).toBeVisible();
  
  await card.getByRole("button", { name: /remove/i }).click();
  
  await expect(card).not.toBeVisible();
});
